// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `backend`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<LoginResponse> login({
  required LoginRequest request,
  required BridgeConfig config,
}) => RustLib.instance.api.crateApiLogin(request: request, config: config);

Future<LoginResponse> refreshSession({
  required String refreshToken,
  required BridgeConfig config,
}) => RustLib.instance.api.crateApiRefreshSession(
  refreshToken: refreshToken,
  config: config,
);

Future<List<PatientProgramSummary>> getPatientPrograms({
  required String token,
  required BridgeConfig config,
}) => RustLib.instance.api.crateApiGetPatientPrograms(
  token: token,
  config: config,
);

Future<void> submitDayFeedback({
  required String token,
  required SubmitDayFeedbackRequest request,
  required BridgeConfig config,
}) => RustLib.instance.api.crateApiSubmitDayFeedback(
  token: token,
  request: request,
  config: config,
);

Future<void> updateDayCompletion({
  required String token,
  required UpdateDayCompletionRequest request,
  required BridgeConfig config,
}) => RustLib.instance.api.crateApiUpdateDayCompletion(
  token: token,
  request: request,
  config: config,
);

class BridgeConfig {
  final String url;
  final String anonKey;

  const BridgeConfig({required this.url, required this.anonKey});

  @override
  int get hashCode => url.hashCode ^ anonKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeConfig &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          anonKey == other.anonKey;
}

class ExerciseFeedbackInput {
  final String exerciseId;
  final int effort;
  final int pain;
  final String? comment;

  const ExerciseFeedbackInput({
    required this.exerciseId,
    required this.effort,
    required this.pain,
    this.comment,
  });

  @override
  int get hashCode =>
      exerciseId.hashCode ^ effort.hashCode ^ pain.hashCode ^ comment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExerciseFeedbackInput &&
          runtimeType == other.runtimeType &&
          exerciseId == other.exerciseId &&
          effort == other.effort &&
          pain == other.pain &&
          comment == other.comment;
}

class ExerciseInstructionSummary {
  final String exerciseId;
  final String name;
  final String? description;
  final String? videoUrl;
  final int sets;
  final int reps;
  final int? effort;
  final int? pain;
  final String? comment;

  const ExerciseInstructionSummary({
    required this.exerciseId,
    required this.name,
    this.description,
    this.videoUrl,
    required this.sets,
    required this.reps,
    this.effort,
    this.pain,
    this.comment,
  });

  @override
  int get hashCode =>
      exerciseId.hashCode ^
      name.hashCode ^
      description.hashCode ^
      videoUrl.hashCode ^
      sets.hashCode ^
      reps.hashCode ^
      effort.hashCode ^
      pain.hashCode ^
      comment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExerciseInstructionSummary &&
          runtimeType == other.runtimeType &&
          exerciseId == other.exerciseId &&
          name == other.name &&
          description == other.description &&
          videoUrl == other.videoUrl &&
          sets == other.sets &&
          reps == other.reps &&
          effort == other.effort &&
          pain == other.pain &&
          comment == other.comment;
}

class LoginRequest {
  final String email;
  final String password;

  const LoginRequest({required this.email, required this.password});

  @override
  int get hashCode => email.hashCode ^ password.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginRequest &&
          runtimeType == other.runtimeType &&
          email == other.email &&
          password == other.password;
}

class LoginResponse {
  final String accessToken;
  final String? refreshToken;
  final String userId;
  final String userProfileType;

  const LoginResponse({
    required this.accessToken,
    this.refreshToken,
    required this.userId,
    required this.userProfileType,
  });

  @override
  int get hashCode =>
      accessToken.hashCode ^
      refreshToken.hashCode ^
      userId.hashCode ^
      userProfileType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginResponse &&
          runtimeType == other.runtimeType &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          userId == other.userId &&
          userProfileType == other.userProfileType;
}

class PatientProgramSummary {
  final String patientProgramId;
  final String programId;
  final String programName;
  final String? programDescription;
  final List<ProgramDaySummary> days;
  final int progressPercent;
  final double? averageEffort;
  final double? averagePain;

  const PatientProgramSummary({
    required this.patientProgramId,
    required this.programId,
    required this.programName,
    this.programDescription,
    required this.days,
    required this.progressPercent,
    this.averageEffort,
    this.averagePain,
  });

  @override
  int get hashCode =>
      patientProgramId.hashCode ^
      programId.hashCode ^
      programName.hashCode ^
      programDescription.hashCode ^
      days.hashCode ^
      progressPercent.hashCode ^
      averageEffort.hashCode ^
      averagePain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PatientProgramSummary &&
          runtimeType == other.runtimeType &&
          patientProgramId == other.patientProgramId &&
          programId == other.programId &&
          programName == other.programName &&
          programDescription == other.programDescription &&
          days == other.days &&
          progressPercent == other.progressPercent &&
          averageEffort == other.averageEffort &&
          averagePain == other.averagePain;
}

class ProgramDaySummary {
  final int dayIndex;
  final int dayNumber;
  final String? workoutName;
  final String? workoutDescription;
  final bool isRestDay;
  final String? sessionDate;
  final String? completedAt;
  final List<ExerciseInstructionSummary> exercises;

  const ProgramDaySummary({
    required this.dayIndex,
    required this.dayNumber,
    this.workoutName,
    this.workoutDescription,
    required this.isRestDay,
    this.sessionDate,
    this.completedAt,
    required this.exercises,
  });

  @override
  int get hashCode =>
      dayIndex.hashCode ^
      dayNumber.hashCode ^
      workoutName.hashCode ^
      workoutDescription.hashCode ^
      isRestDay.hashCode ^
      sessionDate.hashCode ^
      completedAt.hashCode ^
      exercises.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgramDaySummary &&
          runtimeType == other.runtimeType &&
          dayIndex == other.dayIndex &&
          dayNumber == other.dayNumber &&
          workoutName == other.workoutName &&
          workoutDescription == other.workoutDescription &&
          isRestDay == other.isRestDay &&
          sessionDate == other.sessionDate &&
          completedAt == other.completedAt &&
          exercises == other.exercises;
}

class SubmitDayFeedbackRequest {
  final String patientProgramId;
  final int dayIndex;
  final String sessionDate;
  final List<ExerciseFeedbackInput> feedback;

  const SubmitDayFeedbackRequest({
    required this.patientProgramId,
    required this.dayIndex,
    required this.sessionDate,
    required this.feedback,
  });

  @override
  int get hashCode =>
      patientProgramId.hashCode ^
      dayIndex.hashCode ^
      sessionDate.hashCode ^
      feedback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubmitDayFeedbackRequest &&
          runtimeType == other.runtimeType &&
          patientProgramId == other.patientProgramId &&
          dayIndex == other.dayIndex &&
          sessionDate == other.sessionDate &&
          feedback == other.feedback;
}

class UpdateDayCompletionRequest {
  final String patientProgramId;
  final int dayIndex;
  final String sessionDate;
  final bool completed;

  const UpdateDayCompletionRequest({
    required this.patientProgramId,
    required this.dayIndex,
    required this.sessionDate,
    required this.completed,
  });

  @override
  int get hashCode =>
      patientProgramId.hashCode ^
      dayIndex.hashCode ^
      sessionDate.hashCode ^
      completed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateDayCompletionRequest &&
          runtimeType == other.runtimeType &&
          patientProgramId == other.patientProgramId &&
          dayIndex == other.dayIndex &&
          sessionDate == other.sessionDate &&
          completed == other.completed;
}
