// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -174768471;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mobile_bridge_frb',
        ioDirectory: '../mobile-bridge-frb/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<PatientProgramSummary>> crateApiGetPatientPrograms({
    required String token,
    required BridgeConfig config,
  });

  Future<LoginResponse> crateApiLogin({
    required LoginRequest request,
    required BridgeConfig config,
  });

  Future<void> crateApiSubmitDayFeedback({
    required String token,
    required SubmitDayFeedbackRequest request,
    required BridgeConfig config,
  });

  Future<void> crateApiUpdateDayCompletion({
    required String token,
    required UpdateDayCompletionRequest request,
    required BridgeConfig config,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<PatientProgramSummary>> crateApiGetPatientPrograms({
    required String token,
    required BridgeConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_box_autoadd_bridge_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_patient_program_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetPatientProgramsConstMeta,
        argValues: [token, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetPatientProgramsConstMeta => const TaskConstMeta(
    debugName: "get_patient_programs",
    argNames: ["token", "config"],
  );

  @override
  Future<LoginResponse> crateApiLogin({
    required LoginRequest request,
    required BridgeConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_login_request(request, serializer);
          sse_encode_box_autoadd_bridge_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_login_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLoginConstMeta,
        argValues: [request, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoginConstMeta =>
      const TaskConstMeta(debugName: "login", argNames: ["request", "config"]);

  @override
  Future<void> crateApiSubmitDayFeedback({
    required String token,
    required SubmitDayFeedbackRequest request,
    required BridgeConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_box_autoadd_submit_day_feedback_request(
            request,
            serializer,
          );
          sse_encode_box_autoadd_bridge_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSubmitDayFeedbackConstMeta,
        argValues: [token, request, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSubmitDayFeedbackConstMeta => const TaskConstMeta(
    debugName: "submit_day_feedback",
    argNames: ["token", "request", "config"],
  );

  @override
  Future<void> crateApiUpdateDayCompletion({
    required String token,
    required UpdateDayCompletionRequest request,
    required BridgeConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_box_autoadd_update_day_completion_request(
            request,
            serializer,
          );
          sse_encode_box_autoadd_bridge_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUpdateDayCompletionConstMeta,
        argValues: [token, request, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateDayCompletionConstMeta =>
      const TaskConstMeta(
        debugName: "update_day_completion",
        argNames: ["token", "request", "config"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeConfig dco_decode_box_autoadd_bridge_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_config(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  LoginRequest dco_decode_box_autoadd_login_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_login_request(raw);
  }

  @protected
  SubmitDayFeedbackRequest dco_decode_box_autoadd_submit_day_feedback_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_submit_day_feedback_request(raw);
  }

  @protected
  UpdateDayCompletionRequest
  dco_decode_box_autoadd_update_day_completion_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_update_day_completion_request(raw);
  }

  @protected
  BridgeConfig dco_decode_bridge_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeConfig(
      url: dco_decode_String(arr[0]),
      anonKey: dco_decode_String(arr[1]),
    );
  }

  @protected
  ExerciseFeedbackInput dco_decode_exercise_feedback_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ExerciseFeedbackInput(
      exerciseId: dco_decode_String(arr[0]),
      effort: dco_decode_i_32(arr[1]),
      pain: dco_decode_i_32(arr[2]),
      comment: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  ExerciseInstructionSummary dco_decode_exercise_instruction_summary(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ExerciseInstructionSummary(
      exerciseId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      description: dco_decode_opt_String(arr[2]),
      videoUrl: dco_decode_opt_String(arr[3]),
      sets: dco_decode_i_32(arr[4]),
      reps: dco_decode_i_32(arr[5]),
      effort: dco_decode_opt_box_autoadd_i_32(arr[6]),
      pain: dco_decode_opt_box_autoadd_i_32(arr[7]),
      comment: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<ExerciseFeedbackInput> dco_decode_list_exercise_feedback_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_exercise_feedback_input)
        .toList();
  }

  @protected
  List<ExerciseInstructionSummary> dco_decode_list_exercise_instruction_summary(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_exercise_instruction_summary)
        .toList();
  }

  @protected
  List<PatientProgramSummary> dco_decode_list_patient_program_summary(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_patient_program_summary)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProgramDaySummary> dco_decode_list_program_day_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_program_day_summary).toList();
  }

  @protected
  LoginRequest dco_decode_login_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LoginRequest(
      email: dco_decode_String(arr[0]),
      password: dco_decode_String(arr[1]),
    );
  }

  @protected
  LoginResponse dco_decode_login_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LoginResponse(
      accessToken: dco_decode_String(arr[0]),
      userId: dco_decode_String(arr[1]),
      userProfileType: dco_decode_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PatientProgramSummary dco_decode_patient_program_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return PatientProgramSummary(
      patientProgramId: dco_decode_String(arr[0]),
      programId: dco_decode_String(arr[1]),
      programName: dco_decode_String(arr[2]),
      programDescription: dco_decode_opt_String(arr[3]),
      days: dco_decode_list_program_day_summary(arr[4]),
      progressPercent: dco_decode_i_32(arr[5]),
      averageEffort: dco_decode_opt_box_autoadd_f_32(arr[6]),
      averagePain: dco_decode_opt_box_autoadd_f_32(arr[7]),
    );
  }

  @protected
  ProgramDaySummary dco_decode_program_day_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ProgramDaySummary(
      dayIndex: dco_decode_i_32(arr[0]),
      dayNumber: dco_decode_i_32(arr[1]),
      workoutName: dco_decode_opt_String(arr[2]),
      workoutDescription: dco_decode_opt_String(arr[3]),
      isRestDay: dco_decode_bool(arr[4]),
      sessionDate: dco_decode_opt_String(arr[5]),
      completedAt: dco_decode_opt_String(arr[6]),
      exercises: dco_decode_list_exercise_instruction_summary(arr[7]),
    );
  }

  @protected
  SubmitDayFeedbackRequest dco_decode_submit_day_feedback_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SubmitDayFeedbackRequest(
      patientProgramId: dco_decode_String(arr[0]),
      dayIndex: dco_decode_i_32(arr[1]),
      sessionDate: dco_decode_String(arr[2]),
      feedback: dco_decode_list_exercise_feedback_input(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpdateDayCompletionRequest dco_decode_update_day_completion_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return UpdateDayCompletionRequest(
      patientProgramId: dco_decode_String(arr[0]),
      dayIndex: dco_decode_i_32(arr[1]),
      sessionDate: dco_decode_String(arr[2]),
      completed: dco_decode_bool(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeConfig sse_decode_box_autoadd_bridge_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_config(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  LoginRequest sse_decode_box_autoadd_login_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_login_request(deserializer));
  }

  @protected
  SubmitDayFeedbackRequest sse_decode_box_autoadd_submit_day_feedback_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_submit_day_feedback_request(deserializer));
  }

  @protected
  UpdateDayCompletionRequest
  sse_decode_box_autoadd_update_day_completion_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_update_day_completion_request(deserializer));
  }

  @protected
  BridgeConfig sse_decode_bridge_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_anonKey = sse_decode_String(deserializer);
    return BridgeConfig(url: var_url, anonKey: var_anonKey);
  }

  @protected
  ExerciseFeedbackInput sse_decode_exercise_feedback_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_exerciseId = sse_decode_String(deserializer);
    var var_effort = sse_decode_i_32(deserializer);
    var var_pain = sse_decode_i_32(deserializer);
    var var_comment = sse_decode_opt_String(deserializer);
    return ExerciseFeedbackInput(
      exerciseId: var_exerciseId,
      effort: var_effort,
      pain: var_pain,
      comment: var_comment,
    );
  }

  @protected
  ExerciseInstructionSummary sse_decode_exercise_instruction_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_exerciseId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    var var_videoUrl = sse_decode_opt_String(deserializer);
    var var_sets = sse_decode_i_32(deserializer);
    var var_reps = sse_decode_i_32(deserializer);
    var var_effort = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_pain = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_comment = sse_decode_opt_String(deserializer);
    return ExerciseInstructionSummary(
      exerciseId: var_exerciseId,
      name: var_name,
      description: var_description,
      videoUrl: var_videoUrl,
      sets: var_sets,
      reps: var_reps,
      effort: var_effort,
      pain: var_pain,
      comment: var_comment,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<ExerciseFeedbackInput> sse_decode_list_exercise_feedback_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExerciseFeedbackInput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_exercise_feedback_input(deserializer));
    }
    return ans_;
  }

  @protected
  List<ExerciseInstructionSummary> sse_decode_list_exercise_instruction_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExerciseInstructionSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_exercise_instruction_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<PatientProgramSummary> sse_decode_list_patient_program_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PatientProgramSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_patient_program_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProgramDaySummary> sse_decode_list_program_day_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProgramDaySummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_program_day_summary(deserializer));
    }
    return ans_;
  }

  @protected
  LoginRequest sse_decode_login_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_email = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    return LoginRequest(email: var_email, password: var_password);
  }

  @protected
  LoginResponse sse_decode_login_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_accessToken = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_userProfileType = sse_decode_String(deserializer);
    return LoginResponse(
      accessToken: var_accessToken,
      userId: var_userId,
      userProfileType: var_userProfileType,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PatientProgramSummary sse_decode_patient_program_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_patientProgramId = sse_decode_String(deserializer);
    var var_programId = sse_decode_String(deserializer);
    var var_programName = sse_decode_String(deserializer);
    var var_programDescription = sse_decode_opt_String(deserializer);
    var var_days = sse_decode_list_program_day_summary(deserializer);
    var var_progressPercent = sse_decode_i_32(deserializer);
    var var_averageEffort = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_averagePain = sse_decode_opt_box_autoadd_f_32(deserializer);
    return PatientProgramSummary(
      patientProgramId: var_patientProgramId,
      programId: var_programId,
      programName: var_programName,
      programDescription: var_programDescription,
      days: var_days,
      progressPercent: var_progressPercent,
      averageEffort: var_averageEffort,
      averagePain: var_averagePain,
    );
  }

  @protected
  ProgramDaySummary sse_decode_program_day_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dayIndex = sse_decode_i_32(deserializer);
    var var_dayNumber = sse_decode_i_32(deserializer);
    var var_workoutName = sse_decode_opt_String(deserializer);
    var var_workoutDescription = sse_decode_opt_String(deserializer);
    var var_isRestDay = sse_decode_bool(deserializer);
    var var_sessionDate = sse_decode_opt_String(deserializer);
    var var_completedAt = sse_decode_opt_String(deserializer);
    var var_exercises = sse_decode_list_exercise_instruction_summary(
      deserializer,
    );
    return ProgramDaySummary(
      dayIndex: var_dayIndex,
      dayNumber: var_dayNumber,
      workoutName: var_workoutName,
      workoutDescription: var_workoutDescription,
      isRestDay: var_isRestDay,
      sessionDate: var_sessionDate,
      completedAt: var_completedAt,
      exercises: var_exercises,
    );
  }

  @protected
  SubmitDayFeedbackRequest sse_decode_submit_day_feedback_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_patientProgramId = sse_decode_String(deserializer);
    var var_dayIndex = sse_decode_i_32(deserializer);
    var var_sessionDate = sse_decode_String(deserializer);
    var var_feedback = sse_decode_list_exercise_feedback_input(deserializer);
    return SubmitDayFeedbackRequest(
      patientProgramId: var_patientProgramId,
      dayIndex: var_dayIndex,
      sessionDate: var_sessionDate,
      feedback: var_feedback,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpdateDayCompletionRequest sse_decode_update_day_completion_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_patientProgramId = sse_decode_String(deserializer);
    var var_dayIndex = sse_decode_i_32(deserializer);
    var var_sessionDate = sse_decode_String(deserializer);
    var var_completed = sse_decode_bool(deserializer);
    return UpdateDayCompletionRequest(
      patientProgramId: var_patientProgramId,
      dayIndex: var_dayIndex,
      sessionDate: var_sessionDate,
      completed: var_completed,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bridge_config(
    BridgeConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_login_request(
    LoginRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_login_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_submit_day_feedback_request(
    SubmitDayFeedbackRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_submit_day_feedback_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_update_day_completion_request(
    UpdateDayCompletionRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_update_day_completion_request(self, serializer);
  }

  @protected
  void sse_encode_bridge_config(BridgeConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.anonKey, serializer);
  }

  @protected
  void sse_encode_exercise_feedback_input(
    ExerciseFeedbackInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.exerciseId, serializer);
    sse_encode_i_32(self.effort, serializer);
    sse_encode_i_32(self.pain, serializer);
    sse_encode_opt_String(self.comment, serializer);
  }

  @protected
  void sse_encode_exercise_instruction_summary(
    ExerciseInstructionSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.exerciseId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.description, serializer);
    sse_encode_opt_String(self.videoUrl, serializer);
    sse_encode_i_32(self.sets, serializer);
    sse_encode_i_32(self.reps, serializer);
    sse_encode_opt_box_autoadd_i_32(self.effort, serializer);
    sse_encode_opt_box_autoadd_i_32(self.pain, serializer);
    sse_encode_opt_String(self.comment, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_exercise_feedback_input(
    List<ExerciseFeedbackInput> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_exercise_feedback_input(item, serializer);
    }
  }

  @protected
  void sse_encode_list_exercise_instruction_summary(
    List<ExerciseInstructionSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_exercise_instruction_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_patient_program_summary(
    List<PatientProgramSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_patient_program_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_program_day_summary(
    List<ProgramDaySummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_program_day_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_login_request(LoginRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.email, serializer);
    sse_encode_String(self.password, serializer);
  }

  @protected
  void sse_encode_login_response(LoginResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.accessToken, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.userProfileType, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_patient_program_summary(
    PatientProgramSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.patientProgramId, serializer);
    sse_encode_String(self.programId, serializer);
    sse_encode_String(self.programName, serializer);
    sse_encode_opt_String(self.programDescription, serializer);
    sse_encode_list_program_day_summary(self.days, serializer);
    sse_encode_i_32(self.progressPercent, serializer);
    sse_encode_opt_box_autoadd_f_32(self.averageEffort, serializer);
    sse_encode_opt_box_autoadd_f_32(self.averagePain, serializer);
  }

  @protected
  void sse_encode_program_day_summary(
    ProgramDaySummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.dayIndex, serializer);
    sse_encode_i_32(self.dayNumber, serializer);
    sse_encode_opt_String(self.workoutName, serializer);
    sse_encode_opt_String(self.workoutDescription, serializer);
    sse_encode_bool(self.isRestDay, serializer);
    sse_encode_opt_String(self.sessionDate, serializer);
    sse_encode_opt_String(self.completedAt, serializer);
    sse_encode_list_exercise_instruction_summary(self.exercises, serializer);
  }

  @protected
  void sse_encode_submit_day_feedback_request(
    SubmitDayFeedbackRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.patientProgramId, serializer);
    sse_encode_i_32(self.dayIndex, serializer);
    sse_encode_String(self.sessionDate, serializer);
    sse_encode_list_exercise_feedback_input(self.feedback, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_update_day_completion_request(
    UpdateDayCompletionRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.patientProgramId, serializer);
    sse_encode_i_32(self.dayIndex, serializer);
    sse_encode_String(self.sessionDate, serializer);
    sse_encode_bool(self.completed, serializer);
  }
}
