// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeConfig dco_decode_box_autoadd_bridge_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  LoginRequest dco_decode_box_autoadd_login_request(dynamic raw);

  @protected
  SubmitDayFeedbackRequest dco_decode_box_autoadd_submit_day_feedback_request(
    dynamic raw,
  );

  @protected
  UpdateDayCompletionRequest
  dco_decode_box_autoadd_update_day_completion_request(dynamic raw);

  @protected
  BridgeConfig dco_decode_bridge_config(dynamic raw);

  @protected
  ExerciseFeedbackInput dco_decode_exercise_feedback_input(dynamic raw);

  @protected
  ExerciseInstructionSummary dco_decode_exercise_instruction_summary(
    dynamic raw,
  );

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<ExerciseFeedbackInput> dco_decode_list_exercise_feedback_input(
    dynamic raw,
  );

  @protected
  List<ExerciseInstructionSummary> dco_decode_list_exercise_instruction_summary(
    dynamic raw,
  );

  @protected
  List<PatientProgramSummary> dco_decode_list_patient_program_summary(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProgramDaySummary> dco_decode_list_program_day_summary(dynamic raw);

  @protected
  LoginRequest dco_decode_login_request(dynamic raw);

  @protected
  LoginResponse dco_decode_login_response(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PatientProgramSummary dco_decode_patient_program_summary(dynamic raw);

  @protected
  ProgramDaySummary dco_decode_program_day_summary(dynamic raw);

  @protected
  SubmitDayFeedbackRequest dco_decode_submit_day_feedback_request(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateDayCompletionRequest dco_decode_update_day_completion_request(
    dynamic raw,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeConfig sse_decode_box_autoadd_bridge_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  LoginRequest sse_decode_box_autoadd_login_request(
    SseDeserializer deserializer,
  );

  @protected
  SubmitDayFeedbackRequest sse_decode_box_autoadd_submit_day_feedback_request(
    SseDeserializer deserializer,
  );

  @protected
  UpdateDayCompletionRequest
  sse_decode_box_autoadd_update_day_completion_request(
    SseDeserializer deserializer,
  );

  @protected
  BridgeConfig sse_decode_bridge_config(SseDeserializer deserializer);

  @protected
  ExerciseFeedbackInput sse_decode_exercise_feedback_input(
    SseDeserializer deserializer,
  );

  @protected
  ExerciseInstructionSummary sse_decode_exercise_instruction_summary(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<ExerciseFeedbackInput> sse_decode_list_exercise_feedback_input(
    SseDeserializer deserializer,
  );

  @protected
  List<ExerciseInstructionSummary> sse_decode_list_exercise_instruction_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<PatientProgramSummary> sse_decode_list_patient_program_summary(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProgramDaySummary> sse_decode_list_program_day_summary(
    SseDeserializer deserializer,
  );

  @protected
  LoginRequest sse_decode_login_request(SseDeserializer deserializer);

  @protected
  LoginResponse sse_decode_login_response(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PatientProgramSummary sse_decode_patient_program_summary(
    SseDeserializer deserializer,
  );

  @protected
  ProgramDaySummary sse_decode_program_day_summary(
    SseDeserializer deserializer,
  );

  @protected
  SubmitDayFeedbackRequest sse_decode_submit_day_feedback_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateDayCompletionRequest sse_decode_update_day_completion_request(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_config(
    BridgeConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_login_request(
    LoginRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_submit_day_feedback_request(
    SubmitDayFeedbackRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_update_day_completion_request(
    UpdateDayCompletionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_config(BridgeConfig self, SseSerializer serializer);

  @protected
  void sse_encode_exercise_feedback_input(
    ExerciseFeedbackInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_exercise_instruction_summary(
    ExerciseInstructionSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_exercise_feedback_input(
    List<ExerciseFeedbackInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_exercise_instruction_summary(
    List<ExerciseInstructionSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_patient_program_summary(
    List<PatientProgramSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_program_day_summary(
    List<ProgramDaySummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_login_request(LoginRequest self, SseSerializer serializer);

  @protected
  void sse_encode_login_response(LoginResponse self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_patient_program_summary(
    PatientProgramSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_program_day_summary(
    ProgramDaySummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_submit_day_feedback_request(
    SubmitDayFeedbackRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_day_completion_request(
    UpdateDayCompletionRequest self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
