// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -174768471;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__get_patient_programs_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_patient_programs",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_token = <String>::sse_decode(&mut deserializer);
            let api_config = <crate::api::BridgeConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok =
                            crate::api::get_patient_programs(api_token, api_config).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__login_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "login",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::api::LoginRequest>::sse_decode(&mut deserializer);
            let api_config = <crate::api::BridgeConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::api::login(api_request, api_config).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__submit_day_feedback_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "submit_day_feedback",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_token = <String>::sse_decode(&mut deserializer);
            let api_request = <crate::api::SubmitDayFeedbackRequest>::sse_decode(&mut deserializer);
            let api_config = <crate::api::BridgeConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok =
                            crate::api::submit_day_feedback(api_token, api_request, api_config)
                                .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__update_day_completion_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_day_completion",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_token = <String>::sse_decode(&mut deserializer);
            let api_request =
                <crate::api::UpdateDayCompletionRequest>::sse_decode(&mut deserializer);
            let api_config = <crate::api::BridgeConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok =
                            crate::api::update_day_completion(api_token, api_request, api_config)
                                .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::BridgeConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_url = <String>::sse_decode(deserializer);
        let mut var_anonKey = <String>::sse_decode(deserializer);
        return crate::api::BridgeConfig {
            url: var_url,
            anon_key: var_anonKey,
        };
    }
}

impl SseDecode for crate::api::ExerciseFeedbackInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_exerciseId = <String>::sse_decode(deserializer);
        let mut var_effort = <i32>::sse_decode(deserializer);
        let mut var_pain = <i32>::sse_decode(deserializer);
        let mut var_comment = <Option<String>>::sse_decode(deserializer);
        return crate::api::ExerciseFeedbackInput {
            exercise_id: var_exerciseId,
            effort: var_effort,
            pain: var_pain,
            comment: var_comment,
        };
    }
}

impl SseDecode for crate::api::ExerciseInstructionSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_exerciseId = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_description = <Option<String>>::sse_decode(deserializer);
        let mut var_videoUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_sets = <i32>::sse_decode(deserializer);
        let mut var_reps = <i32>::sse_decode(deserializer);
        let mut var_effort = <Option<i32>>::sse_decode(deserializer);
        let mut var_pain = <Option<i32>>::sse_decode(deserializer);
        let mut var_comment = <Option<String>>::sse_decode(deserializer);
        return crate::api::ExerciseInstructionSummary {
            exercise_id: var_exerciseId,
            name: var_name,
            description: var_description,
            video_url: var_videoUrl,
            sets: var_sets,
            reps: var_reps,
            effort: var_effort,
            pain: var_pain,
            comment: var_comment,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::ExerciseFeedbackInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::ExerciseFeedbackInput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::ExerciseInstructionSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::ExerciseInstructionSummary>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::PatientProgramSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::PatientProgramSummary>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::ProgramDaySummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::ProgramDaySummary>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::LoginRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_email = <String>::sse_decode(deserializer);
        let mut var_password = <String>::sse_decode(deserializer);
        return crate::api::LoginRequest {
            email: var_email,
            password: var_password,
        };
    }
}

impl SseDecode for crate::api::LoginResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_accessToken = <String>::sse_decode(deserializer);
        let mut var_userId = <String>::sse_decode(deserializer);
        let mut var_userProfileType = <String>::sse_decode(deserializer);
        return crate::api::LoginResponse {
            access_token: var_accessToken,
            user_id: var_userId,
            user_profile_type: var_userProfileType,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::PatientProgramSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_patientProgramId = <String>::sse_decode(deserializer);
        let mut var_programId = <String>::sse_decode(deserializer);
        let mut var_programName = <String>::sse_decode(deserializer);
        let mut var_programDescription = <Option<String>>::sse_decode(deserializer);
        let mut var_days = <Vec<crate::api::ProgramDaySummary>>::sse_decode(deserializer);
        return crate::api::PatientProgramSummary {
            patient_program_id: var_patientProgramId,
            program_id: var_programId,
            program_name: var_programName,
            program_description: var_programDescription,
            days: var_days,
        };
    }
}

impl SseDecode for crate::api::ProgramDaySummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_dayIndex = <i32>::sse_decode(deserializer);
        let mut var_dayNumber = <i32>::sse_decode(deserializer);
        let mut var_workoutName = <Option<String>>::sse_decode(deserializer);
        let mut var_workoutDescription = <Option<String>>::sse_decode(deserializer);
        let mut var_isRestDay = <bool>::sse_decode(deserializer);
        let mut var_sessionDate = <Option<String>>::sse_decode(deserializer);
        let mut var_completedAt = <Option<String>>::sse_decode(deserializer);
        let mut var_exercises =
            <Vec<crate::api::ExerciseInstructionSummary>>::sse_decode(deserializer);
        return crate::api::ProgramDaySummary {
            day_index: var_dayIndex,
            day_number: var_dayNumber,
            workout_name: var_workoutName,
            workout_description: var_workoutDescription,
            is_rest_day: var_isRestDay,
            session_date: var_sessionDate,
            completed_at: var_completedAt,
            exercises: var_exercises,
        };
    }
}

impl SseDecode for crate::api::SubmitDayFeedbackRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_patientProgramId = <String>::sse_decode(deserializer);
        let mut var_dayIndex = <i32>::sse_decode(deserializer);
        let mut var_sessionDate = <String>::sse_decode(deserializer);
        let mut var_feedback = <Vec<crate::api::ExerciseFeedbackInput>>::sse_decode(deserializer);
        return crate::api::SubmitDayFeedbackRequest {
            patient_program_id: var_patientProgramId,
            day_index: var_dayIndex,
            session_date: var_sessionDate,
            feedback: var_feedback,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::UpdateDayCompletionRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_patientProgramId = <String>::sse_decode(deserializer);
        let mut var_dayIndex = <i32>::sse_decode(deserializer);
        let mut var_sessionDate = <String>::sse_decode(deserializer);
        let mut var_completed = <bool>::sse_decode(deserializer);
        return crate::api::UpdateDayCompletionRequest {
            patient_program_id: var_patientProgramId,
            day_index: var_dayIndex,
            session_date: var_sessionDate,
            completed: var_completed,
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__get_patient_programs_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__login_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__submit_day_feedback_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__update_day_completion_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::BridgeConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.url.into_into_dart().into_dart(),
            self.anon_key.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::BridgeConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::BridgeConfig> for crate::api::BridgeConfig {
    fn into_into_dart(self) -> crate::api::BridgeConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ExerciseFeedbackInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.exercise_id.into_into_dart().into_dart(),
            self.effort.into_into_dart().into_dart(),
            self.pain.into_into_dart().into_dart(),
            self.comment.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ExerciseFeedbackInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ExerciseFeedbackInput>
    for crate::api::ExerciseFeedbackInput
{
    fn into_into_dart(self) -> crate::api::ExerciseFeedbackInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ExerciseInstructionSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.exercise_id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
            self.video_url.into_into_dart().into_dart(),
            self.sets.into_into_dart().into_dart(),
            self.reps.into_into_dart().into_dart(),
            self.effort.into_into_dart().into_dart(),
            self.pain.into_into_dart().into_dart(),
            self.comment.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ExerciseInstructionSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ExerciseInstructionSummary>
    for crate::api::ExerciseInstructionSummary
{
    fn into_into_dart(self) -> crate::api::ExerciseInstructionSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::LoginRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.email.into_into_dart().into_dart(),
            self.password.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::LoginRequest {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::LoginRequest> for crate::api::LoginRequest {
    fn into_into_dart(self) -> crate::api::LoginRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::LoginResponse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.access_token.into_into_dart().into_dart(),
            self.user_id.into_into_dart().into_dart(),
            self.user_profile_type.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::LoginResponse {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::LoginResponse> for crate::api::LoginResponse {
    fn into_into_dart(self) -> crate::api::LoginResponse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::PatientProgramSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.patient_program_id.into_into_dart().into_dart(),
            self.program_id.into_into_dart().into_dart(),
            self.program_name.into_into_dart().into_dart(),
            self.program_description.into_into_dart().into_dart(),
            self.days.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::PatientProgramSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::PatientProgramSummary>
    for crate::api::PatientProgramSummary
{
    fn into_into_dart(self) -> crate::api::PatientProgramSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ProgramDaySummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.day_index.into_into_dart().into_dart(),
            self.day_number.into_into_dart().into_dart(),
            self.workout_name.into_into_dart().into_dart(),
            self.workout_description.into_into_dart().into_dart(),
            self.is_rest_day.into_into_dart().into_dart(),
            self.session_date.into_into_dart().into_dart(),
            self.completed_at.into_into_dart().into_dart(),
            self.exercises.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ProgramDaySummary {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ProgramDaySummary>
    for crate::api::ProgramDaySummary
{
    fn into_into_dart(self) -> crate::api::ProgramDaySummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::SubmitDayFeedbackRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.patient_program_id.into_into_dart().into_dart(),
            self.day_index.into_into_dart().into_dart(),
            self.session_date.into_into_dart().into_dart(),
            self.feedback.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::SubmitDayFeedbackRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::SubmitDayFeedbackRequest>
    for crate::api::SubmitDayFeedbackRequest
{
    fn into_into_dart(self) -> crate::api::SubmitDayFeedbackRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::UpdateDayCompletionRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.patient_program_id.into_into_dart().into_dart(),
            self.day_index.into_into_dart().into_dart(),
            self.session_date.into_into_dart().into_dart(),
            self.completed.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::UpdateDayCompletionRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::UpdateDayCompletionRequest>
    for crate::api::UpdateDayCompletionRequest
{
    fn into_into_dart(self) -> crate::api::UpdateDayCompletionRequest {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::BridgeConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.url, serializer);
        <String>::sse_encode(self.anon_key, serializer);
    }
}

impl SseEncode for crate::api::ExerciseFeedbackInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.exercise_id, serializer);
        <i32>::sse_encode(self.effort, serializer);
        <i32>::sse_encode(self.pain, serializer);
        <Option<String>>::sse_encode(self.comment, serializer);
    }
}

impl SseEncode for crate::api::ExerciseInstructionSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.exercise_id, serializer);
        <String>::sse_encode(self.name, serializer);
        <Option<String>>::sse_encode(self.description, serializer);
        <Option<String>>::sse_encode(self.video_url, serializer);
        <i32>::sse_encode(self.sets, serializer);
        <i32>::sse_encode(self.reps, serializer);
        <Option<i32>>::sse_encode(self.effort, serializer);
        <Option<i32>>::sse_encode(self.pain, serializer);
        <Option<String>>::sse_encode(self.comment, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::ExerciseFeedbackInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::ExerciseFeedbackInput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::ExerciseInstructionSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::ExerciseInstructionSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::PatientProgramSummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::PatientProgramSummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::ProgramDaySummary> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::ProgramDaySummary>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::LoginRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.email, serializer);
        <String>::sse_encode(self.password, serializer);
    }
}

impl SseEncode for crate::api::LoginResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.access_token, serializer);
        <String>::sse_encode(self.user_id, serializer);
        <String>::sse_encode(self.user_profile_type, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::PatientProgramSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.patient_program_id, serializer);
        <String>::sse_encode(self.program_id, serializer);
        <String>::sse_encode(self.program_name, serializer);
        <Option<String>>::sse_encode(self.program_description, serializer);
        <Vec<crate::api::ProgramDaySummary>>::sse_encode(self.days, serializer);
    }
}

impl SseEncode for crate::api::ProgramDaySummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.day_index, serializer);
        <i32>::sse_encode(self.day_number, serializer);
        <Option<String>>::sse_encode(self.workout_name, serializer);
        <Option<String>>::sse_encode(self.workout_description, serializer);
        <bool>::sse_encode(self.is_rest_day, serializer);
        <Option<String>>::sse_encode(self.session_date, serializer);
        <Option<String>>::sse_encode(self.completed_at, serializer);
        <Vec<crate::api::ExerciseInstructionSummary>>::sse_encode(self.exercises, serializer);
    }
}

impl SseEncode for crate::api::SubmitDayFeedbackRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.patient_program_id, serializer);
        <i32>::sse_encode(self.day_index, serializer);
        <String>::sse_encode(self.session_date, serializer);
        <Vec<crate::api::ExerciseFeedbackInput>>::sse_encode(self.feedback, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::UpdateDayCompletionRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.patient_program_id, serializer);
        <i32>::sse_encode(self.day_index, serializer);
        <String>::sse_encode(self.session_date, serializer);
        <bool>::sse_encode(self.completed, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
